name: github context

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "commit id"
      env:
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        COMMIT_ID: ${{ github.sha }}
      run: 'echo "CommitID: $COMMIT_ID"'
    - name: "github context"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: "settings secret"
      env:
        MY_PASSWORD: ${{ secrets.PASSWORD }}
      run: 'echo "My password: $MY_PASSWORD"'
